added changes
anuragl94/js-code-golf pull request #9
Opened 2022-02-14 11:20 UTC by vikram-zopsmart

2022-02-14 11:51 UTC, anuragl94 commented
Please follow submission rules.

2022-02-25 13:48 UTC, rnishant97 requested changes
Please follow same naming conventions for .min.js as you follow for .js files please add logic for checking characters other than alphabets in Match 3 submission and please minify the submission in Match 3.min.js submission

2022-02-25 18:31 UTC, vikram-zopsmart commented
I have made changes please review it.

2022-02-28 08:38 UTC, anuragl94 approved these changes

2022-02-28 08:38 UTC, merged